services:
  - type: web
    name: radio-icecast
    env: docker
    rootDir: render
    dockerfilePath: Dockerfile
    autoDeploy: true
    healthCheckPath: /status.xsl
  - type: web
    name: python-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:10000 server:server"
